version: "3.8"
services:
  pydev:
    image: dev/tsuki
    build:
      context: .
    working_dir: /remote-dev
    command: sleep infinity
    volumes:
      - ../:/remote-dev
      - ~/.ssh:/home/shirenger/.ssh:ro
